# Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [3]:
import numpy as np

def vander(vec,n,increasing=False):
    if increasing:
        van = np.matrix([x**i for x in vec for i in range(n)]).reshape(n,n)
    else:
        van = np.matrix([x**(n-i-1) for x in vec for i in range(n)]).reshape(n,n)
    return van 

In [4]:
vec = np.array([1,2,3,4,5,6])
n=6
mat = vander(vec,n,True)
print(mat)

[[   1    1    1    1    1    1]
 [   1    2    4    8   16   32]
 [   1    3    9   27   81  243]
 [   1    4   16   64  256 1024]
 [   1    5   25  125  625 3125]
 [   1    6   36  216 1296 7776]]


In [5]:
vec = np.array([1,2,3,4,5,6])
n=6
mat = vander(vec,n,False)
print(mat)

[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]
 [7776 1296  216   36    6    1]]


# Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [6]:
def MovingAvg(ls,windowSize):
    z=0
    m=0
    n=windowSize
    for i in range(len(ls)-windowSize+1):
        s = [z+i for i in ls[m:n]]
        avg = sum(s)/windowSize
        m +=1
        n +=1
        print("y{} = {}".format(i+1,avg))

In [7]:
#ls = [10,20,30,40,50,60,70,80,90,100]
#k=4

ls =  [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k = 3

MovingAvg(ls,k)

y1 = 5.0
y2 = 4.666666666666667
y3 = 5.666666666666667
y4 = 6.666666666666667
y5 = 9.666666666666666
y6 = 28.666666666666668
y7 = 49.333333333333336
y8 = 72.66666666666667
y9 = 84.0
y10 = 93.33333333333333
y11 = 116.33333333333333
